# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Docker build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
    uses: docker/login-action@v1.9.0
    with:
      username: {{ secrets.DOCKER_USERNAME }}
      password: {{ secrets.DOCKER_PASSWORD }}
      
    run: docker pull node
