# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Docker build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    name: Build Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker
        run: docker build -t bull-monitor .

      - name: Test Docker - Express provider
        run: bash test.sh express

      - name: Test Docker - Koa provider
        run: bash test.sh koa

      - name: Docker Push
        run: |
          docker tag bull-monitor samuraitruong/bull-monitor
          docker tag bull-monitor samuraitruong/bull-monitor:$(cat package.json | jq -r ."version")
          docker push samuraitruong/bull-monitor 
          docker push samuraitruong/bull-monitor:$(cat package.json | jq -r ."version")
